# Installing packages, importing packages, and authenticating and mounting Google drive.

In [ ]:
# @title Library installations
!pip install geopandas
!pip install rasterio
!pip install earthpy

In [ ]:
# @title Library imports
import os
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np
#from shapely.geometry import mapping
import rasterio as rio
from rasterio.plot import plotting_extent
from rasterio.plot import show
from rasterio.mask import mask
import earthpy as et
import earthpy.spatial as es
import earthpy.plot as ep
from osgeo import gdal
import pandas as pd
from sklearn.metrics import confusion_matrix
import ee
# Prettier plotting with seaborn
sns.set(font_scale=1.5)

In [ ]:
# @title Mounting the Google drive with requisite permissions
from google.colab import drive
drive.mount('/drive')

Mounted at /drive


In [ ]:
# @title Checking the contents of the Google drive folder which has GEE exports
!ls /drive/My\ Drive/GEE_exports

# Combining tiles and clipping rasters to the shapefile

In [ ]:
!gdalbuildvrt -srcnodata -9999 /drive/My\ Drive/GEE_exports/binary/S2_Cls_Me_2019_20w.vrt /drive/My\ Drive/GEE_exports/binary/S2_Cls_Me_2019_20w*.tif
!gdalwarp -dstnodata -9999 -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/panama2019/panama2019.shp /drive/My\ Drive/GEE_exports/binary/S2_Cls_Me_2019_20w.vrt /drive/My\ Drive/GEE_exports/binary/S2_Cls_Me_2019_20w_clipped.vrt
!gdal_translate -ot Int32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/binary/S2_Cls_Me_2019_20w_clipped.vrt /drive/My\ Drive/GEE_exports/binary/S2_Cls_Me_2019_20w_clipped.tif
!rm /drive/My\ Drive/GEE_exports/binary/S2_Cls_Me_2019_20w_clipped.vrt

In [ ]:
!gdalbuildvrt -srcnodata -9999 /drive/My\ Drive/GEE_exports/S2_Acc_Me_2019_20a_50.vrt /drive/My\ Drive/GEE_exports/S2_Acc_Me_2019_20a_50*.tif
!gdalwarp -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/panama2019/panama2019.shp /drive/My\ Drive/GEE_exports/S2_Acc_Me_2019_20a_50.vrt /drive/My\ Drive/GEE_exports/S2_Acc_Me_2019_20a_50_clipped.vrt
!gdal_translate -ot Int32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/S2_Acc_Me_2019_20a_50_clipped.vrt /drive/My\ Drive/GEE_exports/S2_Acc_Me_2019_20a_50_clipped.tif
!rm /drive/My\ Drive/GEE_exports/S2_Acc_Me_2019_20a_50_clipped.vrt

In [ ]:
#Float32
!gdalbuildvrt /drive/My\ Drive/GEE_exports/percentages/S2_Cls_IC_2019_20w.vrt /drive/My\ Drive/GEE_exports/percentages/S2_Cls_IC_2019_20w*.tif
!gdalwarp -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/panama2019/panama2019.shp /drive/My\ Drive/GEE_exports/percentages/S2_Cls_IC_2019_20w.vrt /drive/My\ Drive/GEE_exports/percentages/S2_Cls_IC_2019_20w_clipped.vrt
!gdal_translate -ot Float32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/percentages/S2_Cls_IC_2019_20w_clipped.vrt /drive/My\ Drive/GEE_exports/percentages/S2_Cls_IC_2019_20w_clipped.tif
!rm /drive/My\ Drive/GEE_exports/percentages/S2_Cls_IC_2019_20w_clipped.vrt

In [ ]:
#Float32
!gdalbuildvrt /drive/My\ Drive/GEE_exports/binary/S2_Cls_IC_2020_20d.vrt /drive/My\ Drive/GEE_exports/binary/S2_Cls_IC_2020_20d*.tif
!gdalwarp -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/panama2019/panama2019.shp /drive/My\ Drive/GEE_exports/binary/S2_Cls_IC_2020_20d.vrt /drive/My\ Drive/GEE_exports/binary/S2_Cls_IC_2020_20d_clipped.vrt
!gdal_translate -ot Int32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/binary/S2_Cls_IC_2020_20d_clipped.vrt /drive/My\ Drive/GEE_exports/binary/S2_Cls_IC_2020_20d_clipped.tif
!rm /drive/My\ Drive/GEE_exports/binary/S2_Cls_IC_2020_20d_clipped.vrt

0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 33511P x 14957L.
Processing input file /drive/My Drive/GEE_exports/binary/S2_Cls_IC_2020_20d.vrt.
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 33511, 14957
0...10...20...30...40...50...60...70...80...90...100 - done.


In [ ]:
!gdalbuildvrt -srcnodata -9999 /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20a_50.vrt /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20a_50*.tif
!gdalwarp -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/panama2019/panama2019.shp /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20a_50.vrt /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20a_50_clipped.vrt
!gdal_translate -ot Int32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20a_50_clipped.vrt /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20a_50_clipped.tif
!rm /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20a_50_clipped.vrt

In [ ]:
#Float32
!gdalbuildvrt -srcnodata -9999 /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20w.vrt /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20w*.tif
!gdalwarp -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/panama2019/panama2019.shp /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20w.vrt /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20w_clipped.vrt
!gdal_translate -ot Int32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20w_clipped.vrt /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20w_clipped.tif
!rm /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20w_clipped.vrt

In [ ]:
#S1S2 Int32
!gdalbuildvrt -srcnodata -9999 /drive/My\ Drive/GEE_exports/S1S2_Cls_IC_2019_20a.vrt /drive/My\ Drive/GEE_exports/S1S2_Cls_IC_2019_20a*.tif
!gdalwarp -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/panama2019/panama2019.shp /drive/My\ Drive/GEE_exports/S1S2_Cls_IC_2019_20a.vrt /drive/My\ Drive/GEE_exports/S1S2_Cls_IC_2019_20a_clipped.vrt
!gdal_translate -ot Int32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/S1S2_Cls_IC_2019_20a_clipped.vrt /drive/My\ Drive/GEE_exports/S1S2_Cls_IC_2019_20a_clipped.tif
!rm /drive/My\ Drive/GEE_exports/S1S2_Cls_IC_2019_20a_clipped.vrt

In [ ]:
#S1S2 Int32
!gdalbuildvrt -srcnodata -9999 /drive/My\ Drive/GEE_exports/S1S2_Acc_IC_2019_20a.vrt /drive/My\ Drive/GEE_exports/S1S2_Acc_IC_2019_20a*.tif
!gdalwarp -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/panama2019/panama2019.shp /drive/My\ Drive/GEE_exports/S1S2_Acc_IC_2019_20a.vrt /drive/My\ Drive/GEE_exports/S1S2_Acc_IC_2019_20a_clipped.vrt
!gdal_translate -ot Int32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/S1S2_Acc_IC_2019_20a_clipped.vrt /drive/My\ Drive/GEE_exports/S1S2_Acc_IC_2019_20a_clipped.tif
!rm /drive/My\ Drive/GEE_exports/S1S2_Acc_IC_2019_20a_clipped.vrt

In [ ]:
# new shapefile
!gdalbuildvrt -srcnodata -9999 /drive/My\ Drive/GEE_exports/S2_Cls_IC_2019_20a.vrt /drive/My\ Drive/GEE_exports/S2_Cls_IC_2019_20a*.tif
!gdalwarp -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/panama20193/panama2019.shp /drive/My\ Drive/GEE_exports/S2_Cls_IC_2019_20a.vrt /drive/My\ Drive/GEE_exports/S2_Cls_IC_2019_20a_clipped.vrt
!gdal_translate -ot Int32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/S2_Cls_IC_2019_20a_clipped.vrt /drive/My\ Drive/GEE_exports/S2_Cls_IC_2019_20a_clipped.tif
!rm /drive/My\ Drive/GEE_exports/S2_Cls_IC_2019_20a_clipped.vrt

In [ ]:
!gdalbuildvrt -srcnodata -9999 /drive/My\ Drive/GEE_exports/s2l8_20m_common.vrt /drive/My\ Drive/GEE_exports/s2l8_20m_common*.tif
!gdalwarp -dstnodata -9999 -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/pan_adm0/PAN_adm0.shp /drive/My\ Drive/GEE_exports/s2l8_20m_common.vrt /drive/My\ Drive/GEE_exports/s2l8_20m_common_clipped.vrt
!gdal_translate -ot Int32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/s2l8_20m_common_clipped.vrt /drive/My\ Drive/GEE_exports/s2l8_20m_common_clipped.tif
!rm /drive/My\ Drive/GEE_exports/S2_Acc_IC_2019_20_clipped.vrt

In [ ]:
!gdalbuildvrt -srcnodata -9999 /drive/My\ Drive/GEE_exports/s2l8_20m_l8fixs2.vrt /drive/My\ Drive/GEE_exports/s2l8_20m_l8fixs2*.tif
!gdalwarp -dstnodata -9999 -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/pan_adm0/PAN_adm0.shp /drive/My\ Drive/GEE_exports/s2l8_20m_l8fixs2.vrt /drive/My\ Drive/GEE_exports/s2l8_20m_l8fixs2_clipped.vrt
!gdal_translate -ot Int32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/s2l8_20m_l8fixs2_clipped.vrt /drive/My\ Drive/GEE_exports/s2l8_20m_l8fixs2_clipped.tif
!rm /drive/My\ Drive/GEE_exports/s2l8_20m_l8fixs2_clipped.vrt

In [ ]:
!gdalbuildvrt -srcnodata -9999 /drive/My\ Drive/GEE_exports/s2l8_20m_s2fixl8.vrt /drive/My\ Drive/GEE_exports/s2l8_20m_s2fixl8*.tif
!gdalwarp -dstnodata -9999 -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/pan_adm0/PAN_adm0.shp /drive/My\ Drive/GEE_exports/s2l8_20m_s2fixl8.vrt /drive/My\ Drive/GEE_exports/s2l8_20m_s2fixl8_clipped.vrt
!gdal_translate -ot Int32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/s2l8_20m_s2fixl8_clipped.vrt /drive/My\ Drive/GEE_exports/s2l8_20m_s2fixl8_clipped.tif
!rm /drive/My\ Drive/GEE_exports/s2l8_20m_s2fixl8_clipped.vrt

In [ ]:
!gdalbuildvrt -srcnodata -9999 /drive/My\ Drive/GEE_exports/pixels/S2_Pix_2019_20w.vrt /drive/My\ Drive/GEE_exports/pixels/S2_Pix_2019_20w*.tif
!gdalwarp -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/panama2019/panama2019.shp /drive/My\ Drive/GEE_exports/pixels/S2_Pix_2019_20w.vrt /drive/My\ Drive/GEE_exports/pixels/S2_Pix_2019_20w_clipped.vrt
!gdal_translate -ot Int32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/pixels/S2_Pix_2019_20w_clipped.vrt /drive/My\ Drive/GEE_exports/pixels/S2_Pix_2019_20w_clipped.tif
!rm /drive/My\ Drive/GEE_exports/pixels/S2_Pix_2019_20w_clipped.vrt

0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 33511P x 14957L.
Processing input file /drive/My Drive/GEE_exports/pixels/S2_Pix_2019_20w.vrt.
Using internal nodata values (e.g. -9999) for image /drive/My Drive/GEE_exports/pixels/S2_Pix_2019_20w.vrt.
Copying nodata values from source /drive/My Drive/GEE_exports/pixels/S2_Pix_2019_20w.vrt to destination /drive/My Drive/GEE_exports/pixels/S2_Pix_2019_20w_clipped.vrt.
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 33511, 14957
0...10...20...30...40...50...60...70...80...90...100 - done.


In [ ]:
!gdalbuildvrt -srcnodata -9999 /drive/My\ Drive/GEE_exports/lc2019_4326.vrt /drive/My\ Drive/GEE_exports/lc2019_4326*.tif
!gdalwarp -dstnodata -9999 -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/panama2019/panama2019.shp /drive/My\ Drive/GEE_exports/lc2019_4326.vrt /drive/My\ Drive/GEE_exports/lc2019_4326_clipped.vrt
!gdal_translate -ot Int32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/lc2019_4326_clipped.vrt /drive/My\ Drive/GEE_exports/lc2019_4326_clipped.tif
!rm /drive/My\ Drive/GEE_exports/lc2019_4326_clipped.vrt

In [ ]:
!gdalbuildvrt -srcnodata -9999 /drive/My\ Drive/GEE_exports/composites/S2_Me_2019_20a.vrt /drive/My\ Drive/GEE_exports/composites/S2_Me_2019_20a*.tif
!gdalwarp -co "COMPRESS=PACKBITS" -co "BIGTIFF=YES" -cutline /drive/My\ Drive/GEE_exports/training\ polygons/L8_Cls_IC_2019_20w.shp /drive/My\ Drive/GEE_exports/composites/S2_Me_2019_20a.vrt /drive/My\ Drive/GEE_exports/composites/S2_Me_2019_20a_clipped.vrt
!gdal_translate -ot Float32 -of GTiff -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 /drive/My\ Drive/GEE_exports/composites/S2_Me_2019_20a_clipped.vrt /drive/My\ Drive/GEE_exports/composites/S2_Me_2019_20a_clipped.tif
!rm /drive/My\ Drive/GEE_exports/composites/S2_Me_2019_20a_clipped.vrt

0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 33511P x 14957L.
Processing input file /drive/My Drive/GEE_exports/composites/S2_Me_2019_20a.vrt.
Using internal nodata values (e.g. -9999) for image /drive/My Drive/GEE_exports/composites/S2_Me_2019_20a.vrt.
Copying nodata values from source /drive/My Drive/GEE_exports/composites/S2_Me_2019_20a.vrt to destination /drive/My Drive/GEE_exports/composites/S2_Me_2019_20a_clipped.vrt.
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 33511, 14957
0...10...20...30...40...50...60...70...80...90...100 - done.


# Opening classification and raw data for generating statistics

In [ ]:
s2_cls_me_20 = gdal.Open("/drive/My Drive/GEE_exports/S2_Cls_Me_2019_20_clipped.tif", gdal.GA_ReadOnly)
s2_cls_ic_20 = gdal.Open("/drive/My Drive/GEE_exports/S2_Cls_IC_2019_20_clipped.tif", gdal.GA_ReadOnly)
s2_acc_me_20 = gdal.Open("/drive/My Drive/GEE_exports/S2_Acc_Me_2019_20_clipped.tif", gdal.GA_ReadOnly)
s2_acc_ic_20 = gdal.Open("/drive/My Drive/GEE_exports/S2_Acc_IC_2019_20_clipped.tif", gdal.GA_ReadOnly)
s2_com_20 = gdal.Open("/drive/My Drive/GEE_exports/Panama2012_20_clipped.tif", gdal.GA_ReadOnly)

In [ ]:
s2_acc_ic_20 = gdal.Open("/drive/My Drive/GEE_exports/S2_Acc_IC_2019_20_clipped.tif", gdal.GA_ReadOnly)
l8_acc_ic_20 = gdal.Open("/drive/My Drive/GEE_exports/L8_Acc_IC_2019_20a_clipped.tif", gdal.GA_ReadOnly)
print('Read both files')
s2_acc_ic_20_array = np.array(s2_acc_ic_20.GetRasterBand(1).ReadAsArray())
s2_acc_ic_20_array = s2_acc_ic_20_array.astype(np.int32)
print('Converted S2 to array')
l8_acc_ic_20_array = np.array(l8_acc_ic_20.GetRasterBand(1).ReadAsArray())
l8_acc_ic_20_array = l8_acc_ic_20_array.astype(np.int32)
print('Converted L8 to array')

In [ ]:
ee.Authenticate()

In [ ]:
ee.Initialize()

In [ ]:
#s2_acc_ic_20 = gdal.Open("/drive/My Drive/GEE_exports/S2_Acc_IC_2019_20_clipped.tif", gdal.GA_ReadOnly).GetRasterBand(1)
#l8_acc_ic_20 = gdal.Open("/drive/My Drive/GEE_exports/L8_Acc_IC_2019_20a_clipped.tif", gdal.GA_ReadOnly).GetRasterBand(1)
s2_acc_ic_20 = ee.Image("users/reetam1/S2_Acc_IC_2019_20_clipped")
l8_acc_ic_20 = ee.Image("users/reetam1/L8_Acc_IC_2019_20a_clipped")
print(type(s2_acc_ic_20))
acc1 = s2_acc_ic_20.where(s2_acc_ic_20.gt(0),0)
acc2 = acc1.where(s2_acc_ic_20.eq(10).And(l8_acc_ic_20.eq(10)),10)
acc3 = acc2.where(s2_acc_ic_20.eq(1).And(l8_acc_ic_20.eq(1)),1)

<class 'ee.image.Image'>


In [ ]:
roi = ee.Geometry.Polygon(
        [[[-83.11420630932491, 9.67791124821118],
          [-83.11420630932491, 7.00411556169122],
          [-77.09369849682491, 7.00411556169122],
          [-77.09369849682491, 9.67791124821118]]], None, False)

In [ ]:
medianFile = 's2l8_20m_common'
medianExport = ee.batch.Export.image.toDrive(image=acc3.unmask(-9999),
                                     region=roi.getInfo()['coordinates'],
                                     description='my_description',
                                     folder='GEE_exports',
                                     fileNamePrefix=medianFile,
                                     scale=20,
                                     maxPixels=3e9)
medianExport.start()
medianExport.status()

In [ ]:
acc1 = s2_acc_ic_20.where(s2_acc_ic_20.gte(0),-1)
acc2 = acc1.where(s2_acc_ic_20.eq(10).And(l8_acc_ic_20.eq(11)),11)
acc3 = acc2.where(s2_acc_ic_20.eq(1).And(l8_acc_ic_20.eq(0)),0)
medianFile = 's2l8_20m_l8fixs2'
medianExport = ee.batch.Export.image.toDrive(image=acc3.unmask(-9999),
                                     region=roi.getInfo()['coordinates'],
                                     description='my_description',
                                     folder='GEE_exports',
                                     fileNamePrefix=medianFile,
                                     scale=20,
                                     maxPixels=3e9)
medianExport.start()
medianExport.status()

In [ ]:
acc1 = s2_acc_ic_20.where(s2_acc_ic_20.gte(0),-1)
acc2 = acc1.where(s2_acc_ic_20.eq(11).And(l8_acc_ic_20.eq(10)),11)
acc3 = acc2.where(s2_acc_ic_20.eq(0).And(l8_acc_ic_20.eq(1)),0)
medianFile = 's2l8_20m_s2fixl8'
medianExport = ee.batch.Export.image.toDrive(image=acc3.unmask(-9999),
                                     region=roi.getInfo()['coordinates'],
                                     description='my_description',
                                     folder='GEE_exports',
                                     fileNamePrefix=medianFile,
                                     scale=20,
                                     maxPixels=3e9)
medianExport.start()
medianExport.status()

In [ ]:
unique, counts = np.unique(s2_acc_ic_20_array, return_counts=True)
print(np.asarray((unique, counts)).T)
unique, counts = np.unique(l8_acc_ic_20_array, return_counts=True)
print(np.asarray((unique, counts)).T)

In [ ]:
confusion_matrix(s2_acc_ic_20_array.flatten(),l8_acc_ic_20_array.flatten())

In [ ]:
s2_acc_me_20_array = np.array(s2_acc_me_20.GetRasterBand(1).ReadAsArray())

print('Median classification accuracy')
print(s2_acc_me_20_array.shape)
print(s2_acc_me_20_array.size)
unique, counts = np.unique(s2_acc_me_20_array, return_counts=True)
print(np.asarray((unique, counts)).T)

Median classification accuracy
(14957, 33511)
501224027
[[    -9999 312443284]
 [        0  52476700]
 [        1  21279779]
 [       10  12109908]
 [       11 102914356]]


In [ ]:
s2_acc_ic_20_array = np.array(s2_acc_ic_20.GetRasterBand(1).ReadAsArray())
s2_acc_ic_20_array = s2_acc_ic_20_array.astype(np.int32)
print('Imagecollection classification accuracy')
print(s2_acc_ic_20_array.shape)
print(s2_acc_ic_20_array.size)
unique, counts = np.unique(s2_acc_ic_20_array, return_counts=True)
print(np.asarray((unique, counts)).T)

Imagecollection classification accuracy
(14957, 33511)
501224027
[[    -9999 312443284]
 [        0  52529609]
 [        1  21226870]
 [       10  10780649]
 [       11 104243615]]


In [ ]:
# Dimensions
l8_me_30_array = np.array(l8_me_30.GetRasterBand(1).ReadAsArray())
l8_ic_30_array = np.array(l8_ic_30.GetRasterBand(1).ReadAsArray())
l8_ic_30_array[l8_ic_30_array>0.5] = 1
l8_ic_30_array[(l8_ic_30_array<= 0.5) & (l8_ic_30_array>=0)] = 0
l8_ic_30_array = l8_ic_30_array.astype(np.int32)
print('Median classification dimensions')
print(l8_me_30_array.shape)
print(l8_me_30_array.size)
unique, counts = np.unique(l8_me_30_array, return_counts=True)
print(np.asarray((unique, counts)).T)
print('Imagecollection classification dimensions')
print(l8_ic_30_array.shape)
print(l8_ic_30_array.size)
unique, counts = np.unique(l8_ic_30_array, return_counts=True)
print(np.asarray((unique, counts)).T)

Median classification dimensions
(9972, 22341)
222784452
[[    -9999 141818360]
 [        0  32156493]
 [        1  48809599]]
Imagecollection classification dimensions
(9972, 22341)
222784452
[[    -9999 141818360]
 [        0  33396955]
 [        1  47569137]]


In [ ]:
median = l8_me_30_array[l8_me_30_array>=0]
imagecollection = l8_ic_30_array[l8_ic_30_array>=0]
confusion_matrix(median,imagecollection)

array([[31414263,   742230],
       [ 1982692, 46826907]])

# Statistics for Median composite classification

In [ ]:
statistics = np.zeros((8,3,2))
for n in range(8):
  print('Opening band',n+1)
  band = l8_com_30.GetRasterBand(n+1)
  array = np.array(band.ReadAsArray())
  forest = array[(l8_me_30_array==1) & (array>=0)]
  nonforest = array[(l8_me_30_array==0) & (array>=0)]
  statistics[n,0,0] = np.mean(forest)
  statistics[n,0,1] = np.mean(nonforest)
  statistics[n,1,0] = np.median(forest)
  statistics[n,1,1] = np.median(nonforest)
  statistics[n,2,0] = np.std(forest)
  statistics[n,2,1] = np.std(nonforest)
  print('Deleting band',n+1)
  del band
  print('Band deleted')
  

In [ ]:
print(statistics)

[[[2.62171906e+02 5.43956360e+02]
  [2.15000000e+02 3.69000000e+02]
  [4.76879517e+02 8.21386230e+02]]

 [[5.17001465e+02 8.75363770e+02]
  [4.71000000e+02 7.14000000e+02]
  [4.66342468e+02 7.82186890e+02]]

 [[3.49068207e+02 8.67059204e+02]
  [2.77500000e+02 6.77000000e+02]
  [4.90537781e+02 8.23377319e+02]]

 [[3.41279419e+03 3.34467358e+03]
  [3.41000000e+03 3.27200000e+03]
  [6.72084045e+02 8.22470886e+02]]

 [[1.55743054e+03 2.36885132e+03]
  [1.53400000e+03 2.27750000e+03]
  [4.18103333e+02 6.01574463e+02]]

 [[6.63938232e+02 1.26421558e+03]
  [6.16000000e+02 1.17400000e+03]
  [2.83187378e+02 4.41781403e+02]]

 [[8.25594723e-01 6.08076334e-01]
  [8.51719320e-01 6.33151710e-01]
  [9.54226255e-02 1.62244305e-01]]

 [[4.02685608e+02 1.29734726e+02]
  [2.25000000e+02 9.50000000e+01]
  [4.66309235e+02 1.15373413e+02]]]


# Statistics for Imagecollection classification

In [ ]:
statistics2 = np.zeros((8,3,2))
for n in range(8):
  print('Opening band',n+1)
  band = l8_com_30.GetRasterBand(n+1)
  array = np.array(band.ReadAsArray())
  forest = array[(l8_ic_30_array==1) & (array>=0)]
  nonforest = array[(l8_ic_30_array==0) & (array>=0)]
  statistics2[n,0,0] = np.mean(forest)
  statistics2[n,0,1] = np.mean(nonforest)
  statistics2[n,1,0] = np.median(forest)
  statistics2[n,1,1] = np.median(nonforest)
  statistics2[n,2,0] = np.std(forest)
  statistics2[n,2,1] = np.std(nonforest)
  print('Deleting band',n+1)
  del band
del array
del forest
del nonforest

Opening band 1
Deleting band 1
Opening band 2
Deleting band 2
Opening band 3
Deleting band 3
Opening band 4
Deleting band 4
Opening band 5
Deleting band 5
Opening band 6
Deleting band 6
Opening band 7
Deleting band 7
Opening band 8
Deleting band 8


In [ ]:
print(statistics2)

[[[2.61432892e+02 5.34559082e+02]
  [2.13000000e+02 3.64000000e+02]
  [4.82272125e+02 8.08080078e+02]]

 [[5.15403748e+02 8.64327209e+02]
  [4.68000000e+02 7.07500000e+02]
  [4.71590210e+02 7.70176147e+02]]

 [[3.47667603e+02 8.49816711e+02]
  [2.75000000e+02 6.62000000e+02]
  [4.96112061e+02 8.13309937e+02]]

 [[3.41109644e+03 3.34961572e+03]
  [3.40800000e+03 3.28100000e+03]
  [6.74322205e+02 8.15039429e+02]]

 [[1.55383496e+03 2.34383228e+03]
  [1.52800000e+03 2.25300000e+03]
  [4.20647369e+02 6.06145752e+02]]

 [[6.61541626e+02 1.24533484e+03]
  [6.12500000e+02 1.15350000e+03]
  [2.85450745e+02 4.44955750e+02]]

 [[8.26445282e-01 6.14968956e-01]
  [8.52622986e-01 6.41849279e-01]
  [9.61581841e-02 1.63302496e-01]]

 [[4.10342896e+02 1.28962387e+02]
  [2.34000000e+02 9.50000000e+01]
  [4.69905273e+02 1.13237236e+02]]]


# Sentinel 2 code

In [ ]:
!gdalbuildvrt -srcnodata -9999 /drive/My\ Drive/GEE_exports/S2_Acc_Me_2019_20.vrt /drive/My\ Drive/GEE_exports/S2_Acc_Me_2019_20*.tif
!gdalwarp -dstnodata -9999 -co "COMPRESS=PACKBITS" -cutline /drive/My\ Drive/GEE_exports/pan_adm0/PAN_adm0.shp /drive/My\ Drive/GEE_exports/S2_Acc_Me_2019_20.vrt /drive/My\ Drive/GEE_exports/S2_Acc_Me_2019_20_clipped.tif

0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 33511P x 14957L.
Processing input file /drive/My Drive/GEE_exports/S2_Acc_Me_2019_20.vrt.
Using internal nodata values (e.g. -9999) for image /drive/My Drive/GEE_exports/S2_Acc_Me_2019_20.vrt.
0...10...20...30...40...50...60...70...80...90...100 - done.


In [ ]:
s2_me_30 = gdal.Open("/drive/My Drive/GEE_exports/S2_Acc_Me_2019_20_clipped.tif", gdal.GA_ReadOnly)
s2_me_30_array = np.array(s2_me_30.GetRasterBand(1).ReadAsArray())
print(s2_me_30_array.shape)
print(s2_me_30_array.size)

(14957, 33511)
501224027
